name: Pull Request Validation

on:
  pull_request:
    branches:
      - '**'  # Áp dụng cho tất cả các branch

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate branch status
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          BASE_BRANCH="${{ github.base_ref }}"
          HEAD_BRANCH="${{ github.head_ref }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"

          git fetch origin $BASE_BRANCH
          git fetch origin $HEAD_BRANCH

          # Kiểm tra nhánh có cập nhật không
          if ! git merge-base --is-ancestor origin/$BASE_BRANCH origin/$HEAD_BRANCH; then
            MESSAGE="⚠️ Cập nhật yêu cầu: Nhánh '$HEAD_BRANCH' cần được cập nhật với '$BASE_BRANCH'.

            Vui lòng thực hiện các bước sau:
            \`\`\`
            git checkout $HEAD_BRANCH
            git fetch origin $BASE_BRANCH
            git rebase origin/$BASE_BRANCH
            git push origin $HEAD_BRANCH --force-with-lease
            \`\`\`"
            echo "$MESSAGE"
            gh pr comment $PR_NUMBER --body "$MESSAGE"
            exit 1
          fi

          # Kiểm tra xung đột
          if git merge-tree $(git merge-base $BASE_BRANCH $HEAD_BRANCH) $BASE_BRANCH $HEAD_BRANCH | grep -q "^++<<<<<<< "; then
            MESSAGE="🔀 Xung đột phát hiện: Có xung đột giữa '$HEAD_BRANCH' và '$BASE_BRANCH'.

            Vui lòng giải quyết xung đột:
            \`\`\`
            git checkout $HEAD_BRANCH
            git fetch origin $BASE_BRANCH
            git rebase origin/$BASE_BRANCH
            # Giải quyết xung đột
            git add .
            git rebase --continue
            git push origin $HEAD_BRANCH --force-with-lease
            \`\`\`"
            echo "$MESSAGE"
            gh pr comment $PR_NUMBER --body "$MESSAGE"
            exit 1
          fi

          echo "✅ Nhánh hợp lệ: '$HEAD_BRANCH' đã cập nhật với '$BASE_BRANCH' và không có xung đột."

  code-quality:
    runs-on: ubuntu-latest
    needs: validate-pr
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
        env:
          SKIP_ENV_VALIDATION: true
        continue-on-error: true

      - name: Build project
        run: npm run build
        env:
          SKIP_ENV_VALIDATION: true
